server:
  port: 80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://macfu:hello@127.0.0.1:7001/eureka
spring:
  application:
    name: consumer-consumer-80
