server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.macfu.po            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://45.78.12.29:3306/macfu8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mysqladmin                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-provider-dept
eureka:
  client:       # 客户端进行eureka注册的配置
    service-url:
      defaultZone: http://macfu:hello@127.0.0.1:7001/eureka
  instance:
    instance-id: dept-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true    # 访问的路径变为ip地址(鼠标在微服务信息上左小角会显示ip地址)
    lease-renewal-interval-in-seconds: 5    # 设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 30  # 如果现在超过了30秒间隔(默认90秒)
info:
  app.name: macfu-microcloud
  company.name: www.macfu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
################################### 引入安全配置模块后不在需要配置文件 #################################################
#Security安全配置项
#security:
#  basic:
#    enabled: true   #启动SpringSecurity
#  user:
#    name: macfu   # 认证用户名
#    password: hello   # 认证密码
#    role: -USER   # 授权角色
#  sessions: stateless   # 设置无状态session(服务器不会保存Session状态)
#  ################################################################################################################